export default [
{id: 'id-01',
  name: 'Глэйси',
  shortName: 'gllacy',
  about: 'Проект из списка HTML Academy "HTML и CSS, уровень 1"',
  link: 'https://greycat20142017.github.io/483989-gllacy/',
  git: 'https://github.com/GreyCat20142017/483989-gllacy',
  description: 'Магазин мороженого Глэйси',
  details: ["Верстка"],
  info: '2 фикс. страницы, 1 слайдер (CSS), 1 форма, popup`ы, подменю',
  adaptive: false,
  IESupport: true
},

{id: 'id-02',
  name: 'Нёрдс',
  shortName: 'nerds',
  about: 'Личный проект на интенсиве HTML Academy "HTML и CSS, уровень 1"',
  link: 'https://greycat20142017.github.io/483989-nerds/',
  git: 'https://github.com/GreyCat20142017/483989-nerds',
  description: 'Сайт дизайн-студии',
  details: ["Верстка"],
  info: '2 фикс. страницы, 1 слайдер (CSS), 1 форма',
  adaptive: false,
  IESupport: true
},

{id: 'id-03',
  name: 'Cat-Energy',
  shortName: 'cat-energy',
  about: 'Личный проект на интенсиве HTML Academy "HTML и CSS, уровень 2"',
  link: 'https://greycat20142017.github.io/483989-cat-energy/',
  git: 'https://github.com/GreyCat20142017/483989-cat-energy',
  description: 'Магазин питания для котов',
  details: ["Верстка", "Gulp", "Less"],
  info: '3 адаптивных страницы, мобильное меню, 1 слайдер (JS), 1 форма',
  adaptive: true,
  IESupport: true
},

{id: 'id-04',
  name: 'Creativia',
  shortName: 'creativia',
  about: 'Просто верстка для тренировки навыков',
  link: 'https://greycat20142017.github.io/creativia/',
  git: 'https://github.com/GreyCat20142017/creativia',
  description: 'Сайт студии web-дизайна',
  details: ["Верстка", "Gulp", "SASS"],
  info: '1 адаптивная страница, мобильное меню, 3 слайдера (JS), 1 форма',
  adaptive: true,
  IESupport: true
},

{id: 'id-05',
  name: 'Memory',
  shortName: 'memory',
  about: 'Просто первое SPA для ознакомления с React',
  link: 'https://greycat20142017.github.io/memory/',
  git: 'https://github.com/GreyCat20142017/memory',
  description: 'Игра по мотивам "Memory game"',
  details: ["React"],
  info: 'React, SPA. 2 адаптивных экрана (экран игры, экран настройки)',
  adaptive: true,
  IESupport: true
},

{id: 'id-06',
  name: 'Kekstagram',
  shortName: 'kekstagram',
  about: 'Личный проект на интенсиве HTML Academy "JavaScript, уровень 1"',
  link: 'https://greycat20142017.github.io/483989-kekstagram/',
  git: 'https://github.com/GreyCat20142017/483989-kekstagram',
  description: 'Cервис просмотра изображений',
  details: ["JS ES5"],
  info: 'Только модули на JS ES5. Верстка - HTML Academy, адаптив',
  adaptive: true,
  IESupport: false
},

{id: 'id-07',
  name: 'Candyshop',
  shortName: 'candyshop',
  about: 'Проект из списка HTML Academy "JavaScript, уровень 1"',
  link: 'https://greycat20142017.github.io/483989-candyshop/',
  git: 'https://github.com/GreyCat20142017/483989-candyshop',
  description: 'Интернет-магазин',
  details: ["JS ES5"],
  info: 'Только модули на JS ES5. Верстка - HTML Academy, фикс. макет',
  adaptive: false,
  IESupport: false
},

{id: 'id-00',
  name: 'Портфолио',
  shortName: 'pf',
  about: 'Чтобы было. И для ознакомления с Bootstrap',
  link: '#',
  git: 'https://github.com/GreyCat20142017/pf',
  description: 'Портфолио',
  details: ["React", "Bootstrap"],
  info: 'Просто попытки применить как можно больше разных классов Bootstrap',
  adaptive: true,
  IESupport: true,
  isCurrentProject: true
},

{id: 'id-08',
  name: 'ArtActive',
  shortName: 'artactive',
  about: 'Просто верстка для тренировки навыков',
  link: 'https://greycat20142017.github.io/artactive/',
  git: 'https://github.com/GreyCat20142017/artactive',
  description: 'Сайт полиграфической студии',
  details: ["Верстка", "Gulp", "SASS"],
  info: '1 адаптивная страница, мобильное меню, индикатор прокрутки',
  adaptive: true,
  IESupport: true
},
{id: 'id-09',
  name: 'Конь',
  shortName: 'knight',
  about: 'Просто игра. Нужно же было к чему-то прикрутить Redux',
  link: 'https://greycat20142017.github.io/knight/',
  git: 'https://github.com/GreyCat20142017/knight',
  description: 'Игра по мотивам одной внешней обработки',
  details: ["React", "Redux"],
  info: 'React, SPA',
  adaptive: true,
  IESupport: false,
  inDev: true
},
{id: 'id-10',
  name: 'Бормотунчик',
  shortName: 'bormo',
  about: 'Набросок интерфейса приложения для ознакомления с Material-UI',
  link: 'https://greycat20142017.github.io/bormo/',
  git: 'https://github.com/GreyCat20142017/bormo',
  description: 'Обучающее приложение',
  details: ["React", "React Router", "Material-UI"],
  info: 'React, SPA',
  adaptive: true,
  IESupport: false,
  inDev: true
}
]
